// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20220109201733_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Entity.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Publicador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLibro");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            IdLibro = 1,
                            Autor = "Robin Sharma",
                            Genero = "Fictions",
                            Precio = 141.0,
                            Publicador = "Jaiko Publishing House",
                            Titulo = "The Monk Who Sold His Ferrari"
                        },
                        new
                        {
                            IdLibro = 2,
                            Autor = "Stiphen Hawking",
                            Genero = "Engineering And Technology",
                            Precio = 149.0,
                            Publicador = "Jaiko Publishing House",
                            Titulo = "The Theory Of Everything"
                        },
                        new
                        {
                            IdLibro = 3,
                            Autor = "Robert Kiyosaki",
                            Genero = "Personal finance",
                            Precio = 288.0,
                            Publicador = "Plata publishing",
                            Titulo = "Rich Dad Poor Dad"
                        });
                });

            modelBuilder.Entity("Entity.Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Name = "Victor Venegas",
                            Password = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            Role = "Administrador",
                            User = "vvenegas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
